# Dependencies
markdown:         kramdown
mathjax: true
#redcarpet:
 #   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
    
highlighter:      rouge

kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Permalinks
permalink:        /:categories/:year/:month/:day/:title/
#absolute_permalinks: true

# Setup
title:            Produced Under Scarcity
tagline:          ''
description:      
url:              https://akhilrao.github.io
#url:              https://github.com/akhilrao
#baseurl:          'https://akhilrao.github.io'

author:
  name:           'Akhil Rao'
  url:             https://akhilrao.github.io
  #url:            https://github.com/akhilrao

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:          https://github.com/akhilrao
  
excerpt_separator: <!--endexcerpt-->

gems: [jekyll-paginate]