# Dependencies
markdown:         redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
    
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            A Model A Day
tagline:          'By Akhil Rao'
description:      
url:              /
baseurl:          /

author:
  name:           'Akhil Rao'
  url:            https://github.com/akhilrao

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:          https://github.com/akhilrao
  
excerpt_separator: <!--endexcerpt-->
