# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            A blog
tagline:          'By Akhil Rao'
description:      
url:              /
baseurl:          /

author:
  name:           'Akhil Rao'
#  url:            

paginate:         5

# Custom vars
#version:          2.1.0

#github:
#  repo:          
