# Dependencies
markdown:         kramdown

highlighter:      rouge

kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Permalinks
permalink:        /:categories/:year/:month/:day/:title/

# Setup
title:            Produced Under Scarcity
tagline:          
description:      'Economics, data science, and words about things'
url:              https://akhilrao.github.io
baseurl:          'https://akhilrao.github.io'

author:
  name:           'Akhil Rao'
  url:             https://akhilrao.github.io
 # gravatar_md5:    26915e5b3ffb1eb6bbba2f069f4b0a8e
  
paginate:         5

# Custom vars
version:          0.1.0

github:
  repo:          https://github.com/akhilrao
  
excerpt_separator: <!--endexcerpt-->

gems: [jekyll-paginate]