# Dependencies
markdown:         kramdown
#redcarpet:
#    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
    
highlighter:      rouge

# Permalinks
permalink:        date
relative_permalinks: false

# Setup
title:            Produced Under Scarcity
tagline:          'By Akhil Rao'
description:      
url:              https://github.com/akhilrao
baseurl:          ''

author:
  name:           'Akhil Rao'
  url:            https://github.com/akhilrao

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:          https://github.com/akhilrao
  
excerpt_separator: <!--endexcerpt-->
